index:
  path: /
  controller: App\Controller\DefaultController::index

redirecthomepage:
  path: /homepage
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'blog_homepage'
    permanent: true
    KeepQueryParams: true